version: '3.2'


networks:
  cluster:

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    volumes:
      - ${DB_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    networks:
      - cluster

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: unless-stopped
    volumes:
      - ${APP_VOLUME}:/var/www/html
    ports:
      - ${APP_PORT}:80
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - NEXTCLOUD_ADMIN_USER=${APP_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${APP_ADMIN_PWD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${APP_TRUSTED_DOMAINS}
    depends_on:
      - db
    networks:
      - cluster

