version: '3'

services:
    db:
        image: postgres:12.2-alpine
        restart: always
        volumes:
            - ${DB_VOLUME}:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    app:    
        image: nextcloud:18.0.2-apache
        restart: always
        volumes:
            - ${DATA_VOLUME}:/var/www/html
        ports:
            - ${NEXTCLOUD_PORT}:80
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
            - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
            - NEXTCLOUD_TABLE_PREFIX=nc_
        depends_on:
            - db

