version: '3.7'


networks:
  cluster:


x-op-restart-policy: &restart_policy
  restart: unless-stopped  # always


services:
  db:
    image: postgres:${POSTGRES_VERSION}
    <<: *restart_policy
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
    networks:
      - cluster

  app:
    image: nextcloud:${NEXTCLOUD_VERSION}
    <<: *restart_policy
    volumes:
      - ${NEXTCLOUD_VOLUME}:/var/www/html
    ports:
      - ${NEXTCLOUD_PORT}:80
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - NEXTCLOUD_ADMIN_USER=${APP_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${APP_ADMIN_PWD}
      - NEXTCLOUD_TABLE_PREFIX=nc_
    depends_on:
      - db
    networks:
      - cluster

